plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/root/.openclaw/workspace/cft-performance-review"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'No build needed'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]